# version format
version: v{build}

branches:
  only:
    - master
    - deployment

# Skipping commits with particular message or from specific user
skip_commits:
  message: "*[skip ci]*"

image: Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

before_build:
  - nuget restore %APPVEYOR_PROJECT_NAME%.sln

build:
  project: build_all.xml

after_build:
  - nuget install Packager -DependencyVersion Highest -OutputDirectory packages # Install Packager
  - ps: $folder = Get-ChildItem -Path packages/Packager.* -Name | Out-String    # Get the installation folder (we don't know the actual version)
  - ps: $firstline = ($folder -split '\r\n')[0]                                 # Get rid of carriage-return
  - ps: $fullpath = "packages/$firstline/lib/net48/Packager.exe --debug"        # Build full path
  - ps: Invoke-Expression $fullpath                                             # Execute the packager: the output is nuget\%APPVEYOR_PROJECT_NAME%-Debug.nuspec
  - nuget pack nuget\%APPVEYOR_PROJECT_NAME%-Debug.nuspec
  - dotnet pack --configuration Release /p:Platform=x64 %APPVEYOR_PROJECT_NAME%/%APPVEYOR_PROJECT_NAME%.csproj
  - ps: set SOLUTION_NAME %APPVEYOR_PROJECT_NAME%
  - ps: set PROJECT_NAME %APPVEYOR_PROJECT_NAME%
  - ps: |-
        $xml = [xml](Get-Content .\$SOLUTION_NAME\$PROJECT_NAME.csproj)
  - ps: $version = $xml.Project.PropertyGroup.Version
  - ps: set VERSION v$version
  - ps: echo "Version is $VERSION"

test: off

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)/bin/
    name: $(APPVEYOR_PROJECT_NAME)
  - path: $(SolutionName)-Debug.*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    type: NuGetPackage
  - path: $(SolutionName)/bin/x64/Release/$(SolutionName).*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Release
    type: NuGetPackage

deploy:
  - provider: GitHub
    release: $env:VERSION
    description: 'Automatic deployment'
    auth_token:
      secure: dUpQSnUT5/m88z1BqHNnRjaxxZzz09CmyqFJr/cAyWjqKeLgnKunlIZlEKAXlNIm
    artifact: $(SolutionName)
    draft: true
    prerelease: false
    on:
      branch: deployment
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    symbol_server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(SolutionName)-Package-Debug
    username: dlebansais
    api_key:
      secure: GOksqNi8I7Vs6dcsfosJvSa9vMaZH3zLQJjnx+ruJy6ZeLF075mifj4MdRI34E8W
    on:
      branch: deployment
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(SolutionName)-Package-Release
    skip_symbols: true
    username: dlebansais
    api_key:
      secure: GOksqNi8I7Vs6dcsfosJvSa9vMaZH3zLQJjnx+ruJy6ZeLF075mifj4MdRI34E8W
    on:
      branch: deployment
